/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSDRAM(void);

/* GPIO_B0_09 (coord C9), LPUART_RX */
/* Routed pin properties */
#define BOARD_INITLPUART3_MODBUSAB_LPUART3_RX_PERIPHERAL                 LPUART3   /*!< Peripheral name */
#define BOARD_INITLPUART3_MODBUSAB_LPUART3_RX_SIGNAL                          RX   /*!< Signal name */

/* GPIO_B0_06 (coord A8), DIR_DE_LPUART3 */
/* Routed pin properties */
#define BOARD_INITLPUART3_MODBUSAB_DIR_DE_LPUART3_PERIPHERAL               GPIO2   /*!< Peripheral name */
#define BOARD_INITLPUART3_MODBUSAB_DIR_DE_LPUART3_SIGNAL                 gpio_io   /*!< Signal name */
#define BOARD_INITLPUART3_MODBUSAB_DIR_DE_LPUART3_CHANNEL                     6U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLPUART3_MODBUSAB_DIR_DE_LPUART3_GPIO                     GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITLPUART3_MODBUSAB_DIR_DE_LPUART3_GPIO_PIN                    6U   /*!< GPIO pin number */
#define BOARD_INITLPUART3_MODBUSAB_DIR_DE_LPUART3_GPIO_PIN_MASK       (1U << 6U)   /*!< GPIO pin mask */
#define BOARD_INITLPUART3_MODBUSAB_DIR_DE_LPUART3_PORT                     GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITLPUART3_MODBUSAB_DIR_DE_LPUART3_PIN                         6U   /*!< PORT pin number */
#define BOARD_INITLPUART3_MODBUSAB_DIR_DE_LPUART3_PIN_MASK            (1U << 6U)   /*!< PORT pin mask */

/* GPIO_EMC_40 (coord A7), DIR_RE_LPUART3 */
/* Routed pin properties */
#define BOARD_INITLPUART3_MODBUSAB_DIR_RE_LPUART3_PERIPHERAL               GPIO3   /*!< Peripheral name */
#define BOARD_INITLPUART3_MODBUSAB_DIR_RE_LPUART3_SIGNAL                 gpio_io   /*!< Signal name */
#define BOARD_INITLPUART3_MODBUSAB_DIR_RE_LPUART3_CHANNEL                    26U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLPUART3_MODBUSAB_DIR_RE_LPUART3_GPIO                     GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITLPUART3_MODBUSAB_DIR_RE_LPUART3_GPIO_PIN                   26U   /*!< GPIO pin number */
#define BOARD_INITLPUART3_MODBUSAB_DIR_RE_LPUART3_GPIO_PIN_MASK      (1U << 26U)   /*!< GPIO pin mask */
#define BOARD_INITLPUART3_MODBUSAB_DIR_RE_LPUART3_PORT                     GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITLPUART3_MODBUSAB_DIR_RE_LPUART3_PIN                        26U   /*!< PORT pin number */
#define BOARD_INITLPUART3_MODBUSAB_DIR_RE_LPUART3_PIN_MASK           (1U << 26U)   /*!< PORT pin mask */

/* GPIO_B0_08 (coord B9), LPUART_TX */
/* Routed pin properties */
#define BOARD_INITLPUART3_MODBUSAB_LPUART_TX_PERIPHERAL                  LPUART3   /*!< Peripheral name */
#define BOARD_INITLPUART3_MODBUSAB_LPUART_TX_SIGNAL                           TX   /*!< Signal name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLPUART3_modbusAB(void);

/* GPIO_B0_05 (coord B8), LED_1 */
/* Routed pin properties */
#define BOARD_INITGPIO_LED_1_PERIPHERAL                                    GPIO2   /*!< Peripheral name */
#define BOARD_INITGPIO_LED_1_SIGNAL                                      gpio_io   /*!< Signal name */
#define BOARD_INITGPIO_LED_1_CHANNEL                                          5U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITGPIO_LED_1_GPIO                                          GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITGPIO_LED_1_GPIO_PIN                                         5U   /*!< GPIO pin number */
#define BOARD_INITGPIO_LED_1_GPIO_PIN_MASK                            (1U << 5U)   /*!< GPIO pin mask */
#define BOARD_INITGPIO_LED_1_PORT                                          GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITGPIO_LED_1_PIN                                              5U   /*!< PORT pin number */
#define BOARD_INITGPIO_LED_1_PIN_MASK                                 (1U << 5U)   /*!< PORT pin mask */

/* GPIO_SD_B1_01 (coord M5), BTN_DEFAULT */
/* Routed pin properties */
#define BOARD_INITGPIO_BTN_DEFAULT_PERIPHERAL                              GPIO3   /*!< Peripheral name */
#define BOARD_INITGPIO_BTN_DEFAULT_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INITGPIO_BTN_DEFAULT_CHANNEL                                    1U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITGPIO_BTN_DEFAULT_GPIO                                    GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITGPIO_BTN_DEFAULT_GPIO_PIN                                   1U   /*!< GPIO pin number */
#define BOARD_INITGPIO_BTN_DEFAULT_GPIO_PIN_MASK                      (1U << 1U)   /*!< GPIO pin mask */
#define BOARD_INITGPIO_BTN_DEFAULT_PORT                                    GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITGPIO_BTN_DEFAULT_PIN                                        1U   /*!< PORT pin number */
#define BOARD_INITGPIO_BTN_DEFAULT_PIN_MASK                           (1U << 1U)   /*!< PORT pin mask */

/* GPIO_SD_B1_03 (coord M4), LED_RUN */
/* Routed pin properties */
#define BOARD_INITGPIO_LED_RUN_PERIPHERAL                                  GPIO3   /*!< Peripheral name */
#define BOARD_INITGPIO_LED_RUN_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITGPIO_LED_RUN_CHANNEL                                        3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITGPIO_LED_RUN_GPIO                                        GPIO3   /*!< GPIO peripheral base pointer */
#define BOARD_INITGPIO_LED_RUN_GPIO_PIN                                       3U   /*!< GPIO pin number */
#define BOARD_INITGPIO_LED_RUN_GPIO_PIN_MASK                          (1U << 3U)   /*!< GPIO pin mask */
#define BOARD_INITGPIO_LED_RUN_PORT                                        GPIO3   /*!< PORT peripheral base pointer */
#define BOARD_INITGPIO_LED_RUN_PIN                                            3U   /*!< PORT pin number */
#define BOARD_INITGPIO_LED_RUN_PIN_MASK                               (1U << 3U)   /*!< PORT pin mask */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitGPIO(void);

/* GPIO_B1_01 (coord B11), LPUART4_RX */
/* Routed pin properties */
#define BOARD_INITLPUART4_DCCABINETAB_LPUART4_RX_PERIPHERAL              LPUART4   /*!< Peripheral name */
#define BOARD_INITLPUART4_DCCABINETAB_LPUART4_RX_SIGNAL                       RX   /*!< Signal name */

/* GPIO_B0_07 (coord A9), DIR_RE_1 */
/* Routed pin properties */
#define BOARD_INITLPUART4_DCCABINETAB_DIR_RE_1_PERIPHERAL                  GPIO2   /*!< Peripheral name */
#define BOARD_INITLPUART4_DCCABINETAB_DIR_RE_1_SIGNAL                    gpio_io   /*!< Signal name */
#define BOARD_INITLPUART4_DCCABINETAB_DIR_RE_1_CHANNEL                        7U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLPUART4_DCCABINETAB_DIR_RE_1_GPIO                        GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITLPUART4_DCCABINETAB_DIR_RE_1_GPIO_PIN                       7U   /*!< GPIO pin number */
#define BOARD_INITLPUART4_DCCABINETAB_DIR_RE_1_GPIO_PIN_MASK          (1U << 7U)   /*!< GPIO pin mask */
#define BOARD_INITLPUART4_DCCABINETAB_DIR_RE_1_PORT                        GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITLPUART4_DCCABINETAB_DIR_RE_1_PIN                            7U   /*!< PORT pin number */
#define BOARD_INITLPUART4_DCCABINETAB_DIR_RE_1_PIN_MASK               (1U << 7U)   /*!< PORT pin mask */

/* GPIO_B0_11 (coord A10), DIR_DE_1 */
/* Routed pin properties */
#define BOARD_INITLPUART4_DCCABINETAB_DIR_DE_1_PERIPHERAL                  GPIO2   /*!< Peripheral name */
#define BOARD_INITLPUART4_DCCABINETAB_DIR_DE_1_SIGNAL                    gpio_io   /*!< Signal name */
#define BOARD_INITLPUART4_DCCABINETAB_DIR_DE_1_CHANNEL                       11U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLPUART4_DCCABINETAB_DIR_DE_1_GPIO                        GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITLPUART4_DCCABINETAB_DIR_DE_1_GPIO_PIN                      11U   /*!< GPIO pin number */
#define BOARD_INITLPUART4_DCCABINETAB_DIR_DE_1_GPIO_PIN_MASK         (1U << 11U)   /*!< GPIO pin mask */
#define BOARD_INITLPUART4_DCCABINETAB_DIR_DE_1_PORT                        GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITLPUART4_DCCABINETAB_DIR_DE_1_PIN                           11U   /*!< PORT pin number */
#define BOARD_INITLPUART4_DCCABINETAB_DIR_DE_1_PIN_MASK              (1U << 11U)   /*!< PORT pin mask */

/* GPIO_B1_00 (coord A11), LPUART4_TX */
/* Routed pin properties */
#define BOARD_INITLPUART4_DCCABINETAB_LPUART_TX_PERIPHERAL               LPUART4   /*!< Peripheral name */
#define BOARD_INITLPUART4_DCCABINETAB_LPUART_TX_SIGNAL                        TX   /*!< Signal name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLPUART4_DCCabinetAB(void);

/* GPIO_AD_B0_01 (coord H10), LPSPI3_SDO */
/* Routed pin properties */
#define BOAD_INITFLASH_LPSPI3_SDO_PERIPHERAL                              LPSPI3   /*!< Peripheral name */
#define BOAD_INITFLASH_LPSPI3_SDO_SIGNAL                                     SDO   /*!< Signal name */

/* GPIO_AD_B0_02 (coord M11), LPSPI3_SDI */
/* Routed pin properties */
#define BOAD_INITFLASH_LPSPI3_SDI_PERIPHERAL                              LPSPI3   /*!< Peripheral name */
#define BOAD_INITFLASH_LPSPI3_SDI_SIGNAL                                     SDI   /*!< Signal name */

/* GPIO_AD_B0_00 (coord M14), LPSPI3_CLK */
/* Routed pin properties */
#define BOAD_INITFLASH_LPSPI3_CLK_PERIPHERAL                              LPSPI3   /*!< Peripheral name */
#define BOAD_INITFLASH_LPSPI3_CLK_SIGNAL                                     SCK   /*!< Signal name */

/* GPIO_AD_B0_15 (coord L10), LPSPI3_CS */
/* Routed pin properties */
#define BOAD_INITFLASH_LPSPI3_CS_PERIPHERAL                                GPIO1   /*!< Peripheral name */
#define BOAD_INITFLASH_LPSPI3_CS_SIGNAL                                  gpio_io   /*!< Signal name */
#define BOAD_INITFLASH_LPSPI3_CS_CHANNEL                                     15U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOAD_INITFLASH_LPSPI3_CS_GPIO                                      GPIO1   /*!< GPIO peripheral base pointer */
#define BOAD_INITFLASH_LPSPI3_CS_GPIO_PIN                                    15U   /*!< GPIO pin number */
#define BOAD_INITFLASH_LPSPI3_CS_GPIO_PIN_MASK                       (1U << 15U)   /*!< GPIO pin mask */
#define BOAD_INITFLASH_LPSPI3_CS_PORT                                      GPIO1   /*!< PORT peripheral base pointer */
#define BOAD_INITFLASH_LPSPI3_CS_PIN                                         15U   /*!< PORT pin number */
#define BOAD_INITFLASH_LPSPI3_CS_PIN_MASK                            (1U << 15U)   /*!< PORT pin mask */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOAD_InitFLASH(void);

/* GPIO_B1_13 (coord D14), LPUART5_RX */
/* Routed pin properties */
#define BOAD_INITLPUART5_DCCABINET232_LPUART5_RX_PERIPHERAL              LPUART5   /*!< Peripheral name */
#define BOAD_INITLPUART5_DCCABINET232_LPUART5_RX_SIGNAL                       RX   /*!< Signal name */

/* GPIO_B1_12 (coord D13), LPUART5_TX */
/* Routed pin properties */
#define BOAD_INITLPUART5_DCCABINET232_LPUART5_TX_PERIPHERAL              LPUART5   /*!< Peripheral name */
#define BOAD_INITLPUART5_DCCABINET232_LPUART5_TX_SIGNAL                       TX   /*!< Signal name */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOAD_InitLPUART5_DCCabinet232(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
